In [1]:
print("Hello World")

Hello World


In [2]:
1+1

2

In [3]:
import numpy as np

In [4]:
ones = np.ones(10)

In [5]:
ones

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [7]:
ones+ones

array([ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.])

In [8]:
ones+ones+ones

array([ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.])

In [9]:
ones*3

array([ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.])

In [10]:
rands = np.random.rand(10)

In [11]:
rands

array([ 0.31361088,  0.53040337,  0.31381428,  0.03116503,  0.8219944 ,
        0.00442343,  0.6455222 ,  0.03521384,  0.5028708 ,  0.64583982])

In [12]:
rands[0]

0.31361087538511145

In [13]:
rands[0:3]

array([ 0.31361088,  0.53040337,  0.31381428])

In [14]:
rands[-3]

0.035213841369366006

In [15]:
rands[np.where(rands < 0.5)]

array([ 0.31361088,  0.31381428,  0.03116503,  0.00442343,  0.03521384])

In [16]:
rands+ones

array([ 1.31361088,  1.53040337,  1.31381428,  1.03116503,  1.8219944 ,
        1.00442343,  1.6455222 ,  1.03521384,  1.5028708 ,  1.64583982])

In [20]:
np.concatenate((ones,rands))

array([ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        0.31361088,  0.53040337,  0.31381428,  0.03116503,  0.8219944 ,
        0.00442343,  0.6455222 ,  0.03521384,  0.5028708 ,  0.64583982])

In [23]:
my_list = range(int(1e4))
my_array = np.arange(int(1e4))

In [24]:
# comparison of python list / numpy array using list comprehension

In [30]:
%%timeit # clocks performance of next line
[i*2 for i in my_list]

695 µs ± 34.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [32]:
%%timeit # clocks performance of next line
my_array*2

6.12 µs ± 327 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
